user_token: вставьте_ваш_токен_вместо_этой_строки

session:
  key: KBTl3J0SxQyGwt0UrZZ5oFHwXQzsLh2JwklMhUud2uE=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: vk1.a.e-1EFPs3f75aFoOR0hgeS5yRMRfiORkActuxFeWrUyJF5yFCqF5Bk5voMORjmC4sGqDwsj3NQ3QQ8jeuRtJfCgVw9pUZ2kyHap7xI1x8Vs3yVroxJ2FASaOXlxd2ZAHwz-k-LqhtUKkjumtdscecUNUe6kIG0nGLCu8no3XapfdekdawxxpbdijpTBCQi-3C0_FExDY7JxKMJ0nk5VQbmA
  group_id: 218784155


