user_token: вставьте_ваш_токен_вместо_этой_строки

session:
  key: KBTl3J0SxQyGwt0UrZZ5oFHwXQzsLh2JwklMhUud2uE=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: group_token
  group_id: 1


